# Constants - replace these with the actual values
COMBAT_RATE = 466
NON_COMBAT_RATE = 266
SPECIAL_NEEDS_COMPENSATION = 2000
MENTAL_HEALTH_COMPENSATION = 1500
FAMILY_CARE_COMPENSATION = 1500
EXTRA_DAYS_COMPENSATION = 300
GRANT_DAILY_RATE = 133
# Vacation rates
VACATION_COMPENSATION_DAILY_THRESHOLD = 60
VACATION_RATE_COMBATANT = 3500
VACATION_RATE_NON_COMBATANT = 1500
VACATION_CHILD_BONUS_COMBATANT = 1000
VACATION_CHILD_BONUS_NON_COMBATANT = 500
